osx_image: xcode8.1
language: objective-c
cache: cocoapods
before_install:
- gem install cocoapods 
script:
- set -o pipefail && xcodebuild build -project yalu102.xcodeproj -xcconfig yalu102.xcconfig CODE_SIGNING_REQUIRED=NO | xcpretty
